export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


export const FETCH_RESULTS_ERROR = "FETCH_RESULTS_ERROR";
export const FETCH_RESULTS_SUCCESS = "FETCH_RESULTS_SUCCESS";
export const FETCH_RESULTS_PENDING = "FETCH_RESULTS_PENDING";
